Repository boostcampwm-2022/Web35-CryptoGraph, pull requests merged in 2022-12, with the labels that each got.

#69 Issue#43/use coin metadata hook
  api_server/app.js
  api_server/data/configData.js
  api_server/dataSample/test.js
  api_server/package.json
  client/.gitignore
  client/components/CoinDetailedInfo/index.tsx
  client/hooks/useCoinMetaData.ts
  client/types/CoinDataTypes.ts
  client/utils/metaDataManages.ts
Labels: FE

#71 Issue#66/treemap refactoring
  client/components/Treechart/index.tsx
  client/hooks/useInterval.ts
  client/pages/_app.tsx
  client/pages/chart/treechart.tsx
  client/pages/chart/treechart/index.tsx
  client/tsconfig.json
Labels: Layout, FE, PR개선점

#72 Issue#68/search bar autocomplete and redirect
  client/components/GNB/index.tsx
  client/components/GNB/searchInput.tsx
  client/pages/chart/runningchart/index.tsx
  client/types/CoinDataTypes.ts
  client/utils/inputBarManager.ts
  client/utils/metaDataManages.ts
Labels: FE

#73 Issue#61/coin selection component
  api_server/data/getData.js
  client/components/CoinSelectController/index.tsx
  client/components/Sidebar/index.tsx
  client/pages/chart/candlechart/index.tsx
Labels: Chart, FE

#74 Issue#67/responsive running
  client/components/RunningChart.tsx
  client/pages/chart/runningchart/index.tsx
Labels: Layout

#80 Issue#75/mainpage chart import
  client/.storybook/main.js
  client/.storybook/preview.js
  client/components/Candlechart/index.tsx
  client/components/ChartPeriodSelector/index.tsx
  client/components/CoinDetailedInfo/index.tsx
  client/components/CoinSelectController/index.tsx
  client/components/GNB/index.tsx
  client/components/Sidebar/index.tsx
  client/constants/ChartConstants.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/detail/[market].tsx
  client/pages/index.tsx
  client/stories/Button.stories.tsx
  client/stories/Button.tsx
  client/stories/Header.stories.tsx
  client/stories/Header.tsx
  client/stories/Introduction.stories.mdx
  client/stories/Page.stories.tsx
  client/stories/Page.tsx
  client/stories/assets/code-brackets.svg
  client/stories/assets/colors.svg
  client/stories/assets/comments.svg
  client/stories/assets/direction.svg
  client/stories/assets/flow.svg
  client/stories/assets/plugin.svg
  client/stories/assets/repo.svg
  client/stories/assets/stackalt.svg
  client/stories/button.css
  client/stories/header.css
  client/stories/page.css
  client/tsconfig.json
  client/utils/chartManager.ts
Labels: Layout, FE, refactoring, PR개선점

#79 Issue#70/realtime coinprice component
  api_server/app.js
  api_server/data/configData.js
  api_server/data/getData.js
  client/components/InfoContainerMobile/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/hooks/useRealTimeUpbitData.ts
  client/pages/detail/[market].tsx
  client/types/CoinPriceTypes.ts
  client/utils/apiManager.ts
Labels: FE

#83 Issue#76/candle chart bug
  client/components/Candlechart/index.tsx
Labels: Bug, Chart

#82 러닝차트 1%에서 업데이트 안되고 멈추던 오류 수정
  client/components/CoinSelectController/index.tsx
  client/components/RunningChart.tsx
  client/hooks/reducers/dataReducer.tsx
  client/pages/chart/runningchart/index.tsx
Labels: Bug, Chart

#85 Issue#81/treemap data binding optimization
  api_server/app.js
  api_server/data/configData.js
  api_server/data/getData.js
  client/components/GNB/searchInput.tsx
  client/components/Treechart/getCoinData.tsx
  client/components/Treechart/index.tsx
  client/hooks/reducers/dataReducer.tsx
  client/package.json
  client/pages/chart/treechart/index.tsx
  client/types/CoinDataTypes.ts
Labels: Chart, FE, refactoring

#86 Issue#84/main chart connect
  client/components/ChartSelectController/index.tsx
  client/components/CoinSelectController/index.tsx
  client/components/RunningChart.tsx
  client/components/Treechart/getCoinData.tsx
  client/components/Treechart/index.tsx
  client/pages/chart/runningchart/index.tsx
  client/pages/chart/treechart/index.tsx
  client/pages/index.tsx
  client/types/ChartTypes.ts
  client/types/CoinDataTypes.ts
Labels: Chart, Layout, refactoring, PR개선점

#94 Issue#30/restrict svg dom element
  .github/workflows/deploy.yml
  client/components/Candlechart/index.tsx
  client/components/Runningchart/index.tsx
  client/constants/ChartConstants.ts
  client/types/ChartTypes.ts
  client/utils/chartManager.ts
Labels: Chart, FE, refactoring

#98 Issue#93/add coin info period selector
  client/components/ChartHeader/index.tsx
  client/components/ChartPeriodSelector/index.tsx
  client/components/RunningChart/index.tsx
  client/pages/detail/[market].tsx
Labels: FE, Component, PR개선점

#97 Issue#91/coin selection event
  client/components/CoinSelectController/index.tsx
  client/components/Runningchart/index.tsx
  client/components/Treechart/index.tsx
  client/pages/index.tsx
  client/types/ChartTypes.ts
Labels: Chart, FE, refactoring

#99 Issue#92/mainpage mobile
  client/components/ChartSelectController/index.tsx
  client/components/CoinDetailedInfo/index.tsx
  client/components/CoinSelectController/index.tsx
  client/components/InfoSidebarContainer/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/components/SwiperableDrawer/index.tsx
  client/components/TabContainer/index.tsx
  client/hooks/useRealTimeCoinListData.ts
  client/pages/detail/[market].tsx
  client/pages/index.tsx
Labels: Layout, FE, Component

#104 Issue#41/add chart sort option
  client/components/Runningchart/index.tsx
  client/components/SortSelectController/index.tsx
  client/components/Treechart/index.tsx
  client/hooks/useRealTimeCoinListData.ts
  client/pages/index.tsx
  client/types/ChartTypes.ts
Labels: Bug, Chart, FE, PR개선점

#106 Issue#102/candle chart volume -> 캔들차트 리팩터링
  README.md
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/types/ChartTypes.ts
  client/utils/chartManager.ts
  data_processing_server/README.md
Labels: refactoring, PR개선점

#111 fix : 추가 fetch하는 분봉 기간 수정 #108
  client/components/Candlechart/index.tsx
Labels: Bug

#110 issue#109/delete-data-reducer-and-build-bug-fix
  client/components/Runningchart/index.tsx
  client/hooks/reducers/dataReducer.tsx
  client/types/ChartTypes.ts
  client/utils/upbitManager.ts
Labels: Bug, refactoring

#114 Issue#107/running chart optimization
  client/components/Runningchart/index.tsx
  client/pages/index.tsx
Labels: Chart, FE, refactoring

#116 Issue#78 #100 /change running bar red,blue + runnning chart scroll
  client/components/Runningchart/index.tsx
  client/components/Treechart/index.tsx
  client/pages/index.tsx
  client/style/colorScale.ts
  client/utils/chartManager.ts
Labels: Chart, Layout

#117 Issue#112/custom hook csr
  client/components/GNB/searchInput.tsx
  client/hooks/useRealTimeUpbitData.ts
  client/hooks/useURL.ts
  client/pages/detail/[market].tsx
Labels: FE, refactoring

#113 Issue#103/detail page style
  client/components/ChartHeader/index.tsx
  client/components/CoinDetailedInfo/index.tsx
  client/components/InfoSidebarContainer/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/pages/_app.tsx
  client/pages/detail/[market].tsx
  client/style/theme.ts
  client/theme.d.ts
Labels: Layout, FE

#124 feat : GNB logo 메인페이지 라우팅 적용 / 로고 좌우 패딩값 일치 / 검색바길이 재조정
  client/components/GNB/index.tsx
  client/components/GNB/searchInput.tsx
Labels: Layout, FE

#122 Issue#120/running descending color bugfix
  client/components/GNB/index.tsx
  client/components/Runningchart/index.tsx
  client/components/Treechart/index.tsx
  client/utils/chartManager.ts
Labels: Bug, Chart

#125 검색바 성능개선 Issue#87/search bar click fix
  client/components/GNB/searchInput.tsx
Labels: FE, Component

#126 Issue#118/connect detail main
  client/components/ChartSelectController/index.tsx
  client/components/Modal/index.tsx
  client/components/Runningchart/index.tsx
  client/components/SortSelectController/index.tsx
  client/components/SwiperableDrawer/index.tsx
  client/components/TabContainer/index.tsx
  client/components/Treechart/index.tsx
  client/package-lock.json
  client/package.json
  client/pages/detail/[market].tsx
  client/pages/index.tsx
  client/public/doge.svg
  client/utils/chartManager.ts
Labels: Layout, FE

#129 Issue#96/candle chart refactor
  api_server/data/configData.js
  api_server/data/getData.js
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/components/ChartHeader/index.tsx
  client/constants/ChartConstants.ts
  client/hooks/useRealTimeUpbitData.ts
  client/pages/detail/[market].tsx
  client/types/ChartTypes.ts
  client/utils/chartManager.ts
  client/utils/upbitManager.ts
Labels: Chart, FE

#133 Issue#132 gnb 라우팅+스타일링 / issue#88 오픈그래프 추가
  client/components/GNB/SearchInput.tsx
  client/components/GNB/index.tsx
  client/pages/_document.tsx
  client/public/doge_thumbnail.png
  client/public/favicon.ico
Labels: Bug, Layout, FE

#134 Issue#127/404 page 및 작업 다수
  client/components/Candlechart/index.tsx
  client/components/ChartHeader/index.tsx
  client/components/ChartSelectController/index.tsx
  client/components/CoinDetailedInfo/index.tsx
  client/components/CoinSelectController/SearchCoin.tsx
  client/components/CoinSelectController/index.tsx
  client/components/InfoSidebarContainer/index.tsx
  client/components/LinkButton/index.tsx
  client/components/NoSelectedCoinAlertView/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/components/Runningchart/index.tsx
  client/components/SortSelectController/index.tsx
  client/components/SwiperableDrawer/index.tsx
  client/components/TabBox/index.tsx
  client/components/TabContainer/index.tsx
  client/components/Treechart/index.tsx
  client/hooks/useRealTimeUpbitData.ts
  client/hooks/useUserAgent.ts
  client/pages/404.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/detail/[market].tsx
  client/pages/detail/index.tsx
  client/pages/index.tsx
  client/style/theme.ts
Labels: Layout, FE, upbitAPI

#137 issue#135 트리/러닝 차트 이벤트 버블링 수정
  client/components/Runningchart/index.tsx
  client/components/Treechart/index.tsx
Labels: Bug, Chart

#142 fix : setInterval delay 타입지정 및 예외처리
  client/hooks/useInterval.ts
Labels: Bug

#139 Issue#131/mainpage add chart label
  client/components/ChartTagController/index.tsx
  client/components/CoinSelectController/SearchCoin.tsx
  client/components/Runningchart/index.tsx
  client/components/SortSelectController/index.tsx
  client/components/Treechart/index.tsx
  client/constants/ChartConstants.ts
  client/pages/index.tsx
  client/types/ChartTypes.ts
  client/utils/chartManager.ts
Labels: Bug, Chart, FE, refactoring

#148 각종 css style을 css in js 로 통일 및 안쓰는 console.log, 주석처리 제거
  client/components/Candlechart/index.tsx
  client/components/CoinSelectController/index.tsx
  client/components/GNB/SearchInput.tsx
  client/components/GNB/index.tsx
  client/components/LinkButton/index.tsx
  client/components/Modal/index.tsx
  client/components/Runningchart/index.tsx
  client/components/Treechart/index.tsx
  client/pages/index.tsx
Labels: refactoring

#143 feat : 모바일 캔들차트 줌 이벤트 #59
  client/components/Candlechart/chartController.ts
Labels: Chart, FE

#150 Issue#144/rt price comp improve
  client/components/CoinSelectController/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/hooks/useRealTimeUpbitData.ts
  client/pages/_app.tsx
Labels: Component

#151 fix: 캔들차트 추가 데이터 fetching시 429에러 발생 수정 #136
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/constants/ChartConstants.ts
  client/types/ChartTypes.ts
  client/utils/chartManager.ts
  client/utils/upbitManager.ts
Labels: Bug, Chart

#158 fix: 초기 주봉 데이터 200개 미만 오류수정 #157
  client/components/Candlechart/chartController.ts
Labels: Bug, Chart

#156 fix : 모바일 로고 이슈 해결 #154
  client/components/GNB/LogoImg.tsx
  client/components/GNB/index.tsx
  client/components/GNB/logo-only-white.svg
  client/components/GNB/logo-white.svg
Labels: Bug, FE

#159 Issue#155/optimize detail page render
  api_server/dataSample/priceTest.js
  api_server/dataSample/test.js
  client/components/CoinDetailedInfo/index.tsx
  client/components/LinkButton/index.tsx
  client/hooks/useInterval.ts
  client/hooks/useRealTimeUpbitData.ts
Labels: refactoring

#153 Issue#152/treechart performance 및 이것저것 많이 수정 (완료)
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/components/ChartSelectController/index.tsx
  client/components/CoinSelectController/index.tsx
  client/components/GNB/SearchInput.tsx
  client/components/InfoSidebarContainer/index.tsx
  client/components/Modal/index.tsx
  client/components/NoSelectedCoinAlertView/index.tsx
  client/components/Runningchart/index.tsx
  client/components/SortSelectController/index.tsx
  client/components/SwiperableDrawer/index.tsx
  client/components/TabContainer/index.tsx
  client/components/Treechart/index.tsx
  client/constants/ChartConstants.ts
  client/hooks/useRefElementSize.ts
  client/pages/404.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/detail/[market].tsx
  client/pages/doge.svg
  client/pages/index.tsx
  client/public/doge_thumbnail.png
  client/public/fonts/LINESeedKR-Bd.woff
  client/public/fonts/LINESeedKR-Rg.woff
  client/public/fonts/LINESeedKR-Th.woff
  client/public/fonts/style.css
  client/style/theme.ts
  client/utils/chartManager.ts
Labels: Chart, refactoring

#161 Issue#160/mobile zoom closure
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/components/Candlechart/mobileTouchEventClosure.ts
  client/components/CoinSelectController/SearchCoin.tsx
  client/components/CoinSelectController/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/components/Runningchart/index.tsx
  client/components/SwiperableDrawer/index.tsx
  client/components/TabContainer/index.tsx
  client/components/Treechart/index.tsx
  client/hooks/useRefElementSize.ts
  client/hooks/useUserAgent.ts
  client/pages/_document.tsx
  client/utils/chartManager.ts
Labels: refactoring

#163 Issue#162/main socket refactoring
  client/components/Candlechart/chartController.ts
  client/components/Candlechart/index.tsx
  client/components/RealTimeCoinPrice/index.tsx
  client/components/Runningchart/index.tsx
  client/hooks/useInterval.ts
  client/hooks/useRealTimeCoinListData.ts
  client/hooks/useRealTimeUpbitData.ts
  client/pages/index.tsx
  client/utils/chartManager.ts
  client/utils/dateManager.ts
Labels: refactoring
